### ISSUE TITLE
通用方法意见

### ISSUE THREAD

**Issue by wdd000** [topfullstack/nestjs-mongoose-crud#1]
1.每个通用方法在操作数据库之前能挂一个钩子抛出来给到调用者来改变要更改的实体。这样可以使用时候灵活操作
2.在改变数据库时候有个log装饰器 抛出来可以自定义一些日志记录

**Comment by wxs77577** [comment]
1. 可以考虑
2. 可以使用 `mongoose.set('debug', true)` 在终端显示MongoDB操作语句

**Comment by wxs77577** [comment]
已经更新, 可以传递 `transform`函数 给 `create` 和 `update` 路由
