### ISSUE TITLE
app.module里导入多个Module，说明被覆盖问题

### ISSUE THREAD

**Issue by wdd000** [topfullstack/nestjs-mongoose-crud#2]
app.module里面 如果导入多个Module，例如一个module里面重写方法说明，另外一个module会被覆盖掉  ，导致最后swagger里面显示公共方法都是同样的说明

**Comment by wdd000** [comment]
初步怀疑可能是克隆方法的问题，具体没看出来哪里有问题。

**Comment by wxs77577** [comment]
收到， 我检查一下
