### ISSUE TITLE
所有方法都加一个数据回传前的钩子函数

### ISSUE THREAD

**Issue by wdd000** [topfullstack/nestjs-mongoose-crud#4]
遇到一个问题 ，请求数据时候需要更改数据的结构  ，find方法  需要一个包装后的response，例如：{code：200，data：数据}，使用@crud find里面的populate填充不行  只能另外写方法包装一遍find方法，感觉很麻烦，抛出一个方法提供2次包装最好

**Comment by wxs77577** [comment]
https://docs.nestjs.com/interceptors 参考一下这个

**Comment by wdd000** [comment]
OK
了解  解决了！
