### ISSUE TITLE
swagger get请求参数问题

### ISSUE THREAD

**Issue by pengxingwang** [topfullstack/nestjs-mongoose-crud#7]
>环境：
  "nestjs-mongoose-crud": "^1.2.2",
  "swagger-ui-express": "^4.1.3",
  "@nestjs/swagger": "^4.3.1",

**问题：get请求，用swagger请求时，参数不对，query没有加上去**
![image](https://user-images.githubusercontent.com/26086540/76212549-acd20f80-6243-11ea-8e0b-657b1c0ec04e.png)

**期望：**
![image](https://user-images.githubusercontent.com/26086540/76212599-d1c68280-6243-11ea-94b6-97461cab852f.png)

**Comment by vincentCheng** [comment]
我也遇到过这个问题！
