### ISSUE TITLE
知道原因了，nestjs版本的问题

### ISSUE THREAD

**Issue by zh6391887** [topfullstack/nestjs-mongoose-crud#8]
看到源码里比原来的有改动，用了个ctx代替是原来的req，然后在get时就报了ctx.switchToHttp is not a function的错。

**Comment by JianCunGe** [comment]
return ctx; or  start from const req = ctx.switchToHttp().getRequest();  Delete ...

**Comment by wxs77577** [comment]
是的，`nestjs 7.0`以上对应`nestjs-mongoose-crud@2`
